---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
# Rthink

<!-- badges: start -->
<!-- badges: end -->


This repository contains my own personal notes, code, and code to work through examples and problem sets for the textbook [Statistical Rethinking - *A Bayesian Course with Examples in R and Stan*](https://xcelab.net/rm/statistical-rethinking/)" by Richard Mcelreath.  This repository is not endorsed by anyone affiliated with the textbook they are simply notes. 

### Book Resources: 
[lectures](https://www.youtube.com/watch?v=4WVelCswXo4&list=PLDcUM9US4XdNM4Edgs7weiyIguLSToZRI)  
[course website](https://xcelab.net/rm/statistical-rethinking/)  
[stan translation](https://vincentarelbundock.github.io/rethinking2/)  
[brms translation](https://bookdown.org/content/4857/)  
[R-INLA translation](https://akawiecki.github.io/statistical_rethinking_inla/)  
[julia translation](https://github.com/StatisticalRethinkingJulia)  

```{r,echo=FALSE, fig.width=3.5, fig.height = 3.5}
set.seed(1)
suppressMessages(library(rethinking))
n_samples = 1000 
p = rep( NA , n_samples ) 
p[1] = 0.5
W = 6 
L = 3 

for ( i in 2:n_samples ) {
  p_new <- rnorm( n = 1 ,mean =  p[i-1] , sd = 0.1 )
  if ( p_new < 0 ) p_new <- abs( p_new )
  if ( p_new > 1 ) p_new <- 2 - p_new
  q0 <- dbinom(x =  W , size =  W+L , prob =  p[i-1] )
  q1 <- dbinom( x = W , size = W+L ,prob =  p_new )
  p[i] <- ifelse( runif(1) < q1/q0 , p_new , p[i-1] )
}

dens( p , xlim=c(0,1),  main = "Small World Globe Toss MCMC")
curve( dbeta( x , W+1 , L+1 ) , lty=2 , add=TRUE )
```

## Rethinking Package functions  
```{r}
lsf.str("package:rethinking") 
```



